/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.grafo;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.openide.util.Exceptions;

/**
 *
 * @author alex
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    GephiG grafo;
    File red;

    public VentanaPrincipal() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonImportar = new javax.swing.JButton();
        botonResaltar = new javax.swing.JButton();
        campoGen = new javax.swing.JTextField();
        botonExportar = new javax.swing.JButton();
        rButtonPDF = new javax.swing.JRadioButton();
        rButtonPNG = new javax.swing.JRadioButton();
        rButtonGML = new javax.swing.JRadioButton();
        rButtonPajek = new javax.swing.JRadioButton();
        rButtonCSV = new javax.swing.JRadioButton();
        botonAbrir = new javax.swing.JButton();
        fieldArchivo = new javax.swing.JTextField();
        rButtonYifanHu = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rButtonJerarquico = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(botonImportar, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.botonImportar.text")); // NOI18N
        botonImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImportarActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(botonResaltar, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.botonResaltar.text")); // NOI18N
        botonResaltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResaltarActionPerformed(evt);
            }
        });

        campoGen.setText(org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.campoGen.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(botonExportar, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.botonExportar.text")); // NOI18N
        botonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExportarActionPerformed(evt);
            }
        });

        rButtonPDF.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(rButtonPDF, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonPDF.text")); // NOI18N
        rButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonPDFActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(rButtonPNG, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonPNG.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rButtonGML, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonGML.text")); // NOI18N
        rButtonGML.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(rButtonPajek, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonPajek.text")); // NOI18N
        rButtonPajek.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(rButtonCSV, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonCSV.text")); // NOI18N
        rButtonCSV.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(botonAbrir, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.botonAbrir.text")); // NOI18N
        botonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirActionPerformed(evt);
            }
        });

        fieldArchivo.setEditable(false);
        fieldArchivo.setText(org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.fieldArchivo.text")); // NOI18N

        rButtonYifanHu.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(rButtonYifanHu, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonYifanHu.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rButtonJerarquico, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.rButtonJerarquico.text")); // NOI18N
        rButtonJerarquico.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonPNG)
                        .addGap(18, 18, 18)
                        .addComponent(rButtonGML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonPajek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonCSV)
                        .addGap(140, 390, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonImportar)))
                .addGap(0, 323, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonResaltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoGen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(rButtonYifanHu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonJerarquico)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonImportar)
                    .addComponent(botonAbrir)
                    .addComponent(fieldArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rButtonYifanHu)
                    .addComponent(jLabel1)
                    .addComponent(rButtonJerarquico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResaltar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonExportar)
                    .addComponent(rButtonPDF)
                    .addComponent(rButtonPNG)
                    .addComponent(rButtonGML)
                    .addComponent(rButtonPajek)
                    .addComponent(rButtonCSV))
                .addContainerGap(508, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1142, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jMenu1, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jMenu1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(menuAbrir, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.menuAbrir.text")); // NOI18N
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbrir);

        org.openide.awt.Mnemonics.setLocalizedText(menuCerrar, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.menuCerrar.text")); // NOI18N
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuCerrar);

        jMenuBar1.add(jMenu1);

        org.openide.awt.Mnemonics.setLocalizedText(jMenu2, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jMenu2.text")); // NOI18N
        jMenuBar1.add(jMenu2);

        org.openide.awt.Mnemonics.setLocalizedText(jMenu3, org.openide.util.NbBundle.getMessage(VentanaPrincipal.class, "VentanaPrincipal.jMenu3.text")); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Agrupamos los radio button para no permitir seleccionar varios
    private void groupButton() {

        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(rButtonPDF);
        bg1.add(rButtonPNG);
        bg1.add(this.rButtonCSV);
        bg1.add(this.rButtonGML);
        bg1.add(this.rButtonPajek);

    }


    private void botonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImportarActionPerformed
        // TODO add your handling code here:
        if (red != null) {
            grafo = new GephiG(red);
            JOptionPane.showMessageDialog(null, "Red importada con éxito");
        } else {
            JOptionPane.showMessageDialog(null, "No se ha importado ninguna red");
        }
    }//GEN-LAST:event_botonImportarActionPerformed

    private void botonResaltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResaltarActionPerformed
        // TODO add your handling code here:
        if (grafo != null) {
            if (grafo.resaltar(campoGen.getText(), grafo.getGraphmodel())) {
                JOptionPane.showMessageDialog(null, "Nodo resaltado junto a sus adyacentes");
            } else {
                JOptionPane.showMessageDialog(null, "No existe el nodo");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "No se ha importado ninguna red");
        }
    }//GEN-LAST:event_botonResaltarActionPerformed

    private void botonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExportarActionPerformed
        // TODO add your handling code here:
        if (grafo != null) {
            //Aplicamos layout
            if (rButtonYifanHu.isSelected()) {
                grafo.aplicarYifanHu();
            }

            //Elegimos la extension deseada
            if (rButtonPDF.isSelected()) {
                if (grafo.exportar("pdf")) {
                    JOptionPane.showMessageDialog(null, "Red exportada con éxito");
                }
            } else if (rButtonPNG.isSelected()) {
                if (grafo.exportar("png")) {
                    JOptionPane.showMessageDialog(null, "Red exportada con éxito");
                }
            } else if (rButtonGML.isSelected()) {
                if (grafo.exportar("gml")) {
                    JOptionPane.showMessageDialog(null, "Red exportada con éxito");
                }
            } else if (rButtonPajek.isSelected()) {
                if (grafo.exportar("pajek")) {
                    JOptionPane.showMessageDialog(null, "Red exportada con éxito");
                }
            } else if (rButtonCSV.isSelected()) {
                if (grafo.exportar("csv")) {
                    JOptionPane.showMessageDialog(null, "Red exportada con éxito");
                }
            }

            BufferedImage myPicture;
            try {
                myPicture = ImageIO.read(new File("red.png"));
                JLabel picLabel = new JLabel(new ImageIcon(myPicture));
                jPanel3.add(picLabel);
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se ha importado ninguna red");
        }
    }//GEN-LAST:event_botonExportarActionPerformed

    private void rButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButtonPDFActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(VentanaPrincipal.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            red = fc.getSelectedFile();
            //This is where a real application would open the file.
            fieldArchivo.setText(red.getName());
        } else {
            fieldArchivo.setText("¡Operacion cancelada!");
        }
        fieldArchivo.setCaretPosition(fieldArchivo.getDocument().getLength());
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        // TODO add your handling code here:
        this.botonAbrirActionPerformed(evt);
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonExportar;
    private javax.swing.JButton botonImportar;
    private javax.swing.JButton botonResaltar;
    private javax.swing.JTextField campoGen;
    private javax.swing.JTextField fieldArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JRadioButton rButtonCSV;
    private javax.swing.JRadioButton rButtonGML;
    private javax.swing.JRadioButton rButtonJerarquico;
    private javax.swing.JRadioButton rButtonPDF;
    private javax.swing.JRadioButton rButtonPNG;
    private javax.swing.JRadioButton rButtonPajek;
    private javax.swing.JRadioButton rButtonYifanHu;
    // End of variables declaration//GEN-END:variables
}
